### ISSUE TITLE
Enable arm64 builds for Linux

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/machine-driver-libvirt#117]
We should build and release arm64 bits for linux as well so that user who want to try arm64 crc linux binary should able to use it.

**Comment by cfergeau** [comment]
Since machine-driver-libvirt cannot be cross-built, the situation is better wrt our RPM builds than admin-helper and crc (see https://github.com/crc-org/admin-helper/issues/53 for example).
We already build RPMs for multiple arches, and the binaries in these RPMs are for the correct arch.
So we only need to release arm64 binaries, they are already built correctly as far as I can tell.

The libvirt XML generated  by machine-driver-libvirt may contain hardcoded x86-specific features though. This needs to be fixed if that is the case.

**Comment by praveenkumar** [comment]
> The libvirt XML generated by machine-driver-libvirt may contain hardcoded x86-specific features though. This needs to be fixed if that is the case.

Yes, we need to fix those.

**Comment by cfergeau** [comment]
Fixed by https://github.com/crc-org/machine-driver-libvirt/pull/119
